"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const arg_1 = __importDefault(require("arg"));
const fs_extra_1 = __importDefault(require("fs-extra"));
const ts_morph_1 = require("ts-morph");
const OBJECT_TYPE = { ENTITY: 'ENTITY', DTO: 'DTO' };
const UNKNOWN = 'UNKNOWN';
const DEFAULT_SOURCE_FOLDER = './src/entity/**/*.ts';
const DEFAULT_DESCRIPTOR_DESTINATION_FOLDER = 'src/util/entity-descriptor.ts';
const DEFAULT_OBJECT_TYPE = OBJECT_TYPE.ENTITY;
const cleanFile = (filePath) => {
    fs_extra_1.default.ensureFileSync(filePath);
    fs_extra_1.default.writeFileSync(filePath, '');
    appendToFile(filePath, `/* This is an autogenerated file. Please do not edit directly. */`);
};
const appendToFile = (filePath, content) => {
    fs_extra_1.default.writeFileSync(filePath, content, { flag: 'a' });
    fs_extra_1.default.writeFileSync(filePath, '\n\n', { flag: 'a' });
};
const prepareHierarchyMap = (sourceFiles) => {
    var _a;
    let map = new Map();
    for (const sourceFile of sourceFiles) {
        const node = sourceFile.getClasses()[0];
        map.set((_a = node.getName()) !== null && _a !== void 0 ? _a : 'UNKNOWN', node);
    }
    return map;
};
const getDescriptorDetails = (classMap, node, className = UNKNOWN, definition) => {
    var _a, _b, _c, _d, _e, _f;
    let extendsClassName = (_b = (_a = node.getStructure().extends) === null || _a === void 0 ? void 0 : _a.toString()) !== null && _b !== void 0 ? _b : undefined;
    let extendsClass = node.getBaseClass();
    if (extendsClassName && classMap) {
        extendsClass = classMap.get(extendsClassName);
    }
    let baseClass = extendsClass;
    //console.log(baseClass?.getName() ?? 'No Base Class found for ' + node.getName());
    if (definition) {
    }
    else {
        definition = {
            FIELDS: {},
            CLASS_NAME: '',
            CLASS_HIERARCHY: [],
        };
    }
    if (baseClass) {
        definition = getDescriptorDetails(classMap, baseClass, className, definition);
        //definition.CLASS_HIERARCHY.push(baseClass.getName());
    }
    const allKeys = node.getProperties().map(p => p.getName());
    for (const property of node.getProperties()) {
        let fieldDescription = {};
        fieldDescription.name = property.getName();
        fieldDescription.isForeignKey = false;
        fieldDescription.type = (_d = (_c = property === null || property === void 0 ? void 0 : property.getType()) === null || _c === void 0 ? void 0 : _c.getText()) !== null && _d !== void 0 ? _d : UNKNOWN;
        // sometimes, getting file_path.className
        if (fieldDescription.type) {
            let fullType = fieldDescription.type.split('.');
            fieldDescription.type = fullType[fullType.length - 1];
            if (classMap.get(fieldDescription.type))
                fieldDescription.isForeignKey = true;
        }
        fieldDescription.decorators =
            (_f = (_e = property.getDecorators()) === null || _e === void 0 ? void 0 : _e.map(decorator => {
                var _a;
                return { name: decorator.getName(), args: (_a = decorator.getArguments()) === null || _a === void 0 ? void 0 : _a.map(argument => argument.getText()) };
            })) !== null && _f !== void 0 ? _f : [];
        if (className === node.getName()) {
            fieldDescription.isInherited = false;
            fieldDescription.inheritedFromClassName = '';
        }
        else {
            fieldDescription.isInherited = true;
            fieldDescription.inheritedFromClassName = node.getName();
        }
        definition.FIELDS[property.getName()] = fieldDescription;
    }
    if (className)
        definition.CLASS_NAME = className;
    if ((node === null || node === void 0 ? void 0 : node.getName()) && className && node.getName() && node.getName() !== className)
        definition.CLASS_HIERARCHY.push(node === null || node === void 0 ? void 0 : node.getName());
    ////console.log(definition);
    return definition;
};
// initName is name of the interface file below the root, ./src is considered the root
const prepareDescriptor = (args) => {
    const project = new ts_morph_1.Project();
    let objectType = args.objectType.toUpperCase();
    let sources = [];
    if (args.includeCommon) {
        if (objectType === OBJECT_TYPE.ENTITY) {
            sources.push('./node_modules/@kaiju-lib/node-common/src/common/entity/**/*.ts');
        }
    }
    sources.push(args.sourcePath);
    console.log('Sources=', sources);
    const sourceFiles = project.addSourceFilesAtPaths(sources);
    let classMap = prepareHierarchyMap(sourceFiles);
    cleanFile(args.destinationPath);
    let allEntitiesMapName = `${objectType}_DESCRIPTOR_MAP`;
    if (sourceFiles && sourceFiles.length > 0) {
        let docsForDescriptorMap = `
    /**
    * Use as follows:
    * ${objectType}_DESCRIPTOR_MAP.get(<ClassName>Descriptor.CLASS_NAME);
    * e.g. : 
    * ${objectType}_DESCRIPTOR_MAP.get(SampleDescriptor.CLASS_NAME);
    * ${objectType}_DESCRIPTOR_MAP.get(UserDescriptor.CLASS_NAME);
    */
   `;
        appendToFile(args.destinationPath, docsForDescriptorMap);
        appendToFile(args.destinationPath, `export const ${allEntitiesMapName}:Map<string,any> = new Map();`);
        for (const sourceFile of sourceFiles) {
            //const sourceFile = project.addSourceFileAtPath(`./src/entity/${intName}.ts`);
            const node = sourceFile.getClasses()[0];
            console.log(`Processing ${node.getName()}`);
            let descriptor = getDescriptorDetails(classMap, node, node.getName(), null);
            //console.log(descriptor);
            if (descriptor) {
                let constName = `${node.getName()}Descriptor`;
                let content = `export const ${constName} = ${JSON.stringify(descriptor)}`;
                appendToFile(args.destinationPath, content);
                appendToFile(args.destinationPath, `${allEntitiesMapName}.set('${node.getName()}', ${constName})`);
            }
        }
    }
};
function parseArgumentsIntoOptions(rawArgs) {
    const args = (0, arg_1.default)({
        '--src': String,
        '--out': String,
        '--type': String,
        '--include-common': Boolean,
        '-s': '--src',
        '-o': '--out',
        '-t': '--type',
        '-c': '--include-common',
    }, {
        argv: rawArgs.slice(2),
        permissive: true,
    });
    return {
        sourcePath: args['--src'] || DEFAULT_SOURCE_FOLDER,
        destinationPath: args['--out'] || DEFAULT_DESCRIPTOR_DESTINATION_FOLDER,
        objectType: args['--type'] || DEFAULT_OBJECT_TYPE,
        includeCommon: args['--include-common'] || false,
    };
}
const run = () => {
    //console.log(process.argv);
    console.log('Starting Code Gen');
    let args = parseArgumentsIntoOptions(process.argv);
    console.log('Arguments=', args);
    prepareDescriptor(args);
    console.log('Completed Code Gen');
};
run();
//# sourceMappingURL=index.js.map