export enum SLACK_OAUTH_STATUS {
  SUCCESS = 'success',
  FAIL = 'fail',
}

export enum SLACK_REDIS_KEYS {
  INSTALL_INFORMATION = 'INSTALL_INFORMATION',
  CONFIG = 'CONFIG',
  CHANNEL_INFO = 'CHANNEL_INFO',
  CHANEL_META_DATA = 'CHANEL_META_DATA',
  DIRECT_MESSAGE_META_DATA = 'DIRECT_MESSAGE_META_DATA',
  THREAD_PROJECT_MAPPING = 'THREAD_PROJECT_MAPPING',
  DIRECT_MESSAGE_THREAD_PROJECT_MAPPING = 'DIRECT_MESSAGE_THREAD_PROJECT_MAPPING',
}

export enum SLACK_EVENTS {
  APP_HOME_OPENED = 'app_home_opened',
  APP_MENTION = 'app_mention',
  MESSAGE = 'message',
  APP_UNINSTALLED = 'app_uninstalled',
}

export enum SLACK_BUTTONS_ACTIONS {
  SAVE_CONFIG_BUTTON = 'SAVE_CONFIG_BUTTON', // TODO: ADD SCREEN IDENTIFIER
  EDIT_CONFIG_BUTTON = 'EDIT_CONFIG_BUTTON',
  UPDATE_CONFIG_BUTTON = 'UPDATE_CONFIG_BUTTON',
  SAVE_PROJECT_SESSION_DETAILS_BUTTON = 'SAVE_PROJECT_SESSION_DETAILS_BUTTON',
  CHANGE_PROJECT_SESSION_YES_BUTTON = 'CHANGE_PROJECT_SESSION_YES_BUTTON',
  CHANGE_PROJECT_SESSION_NO_BUTTON = 'CHANGE_PROJECT_SESSION_NO_BUTTON',
  SUBMIT_VIEW_BUTTON = 'view_submission',
}

export enum SLACK_INPUT_ACTIONS {
  BASE_URL_INPUT = 'BASE_URL_INPUT',
  API_KEY_INPUT = 'API_KEY_INPUT',
  NO_ACTION_INPUT = 'NO_ACTION_INPUT',
}

export enum SLACK_DROPDOWN_ACTIONS {
  PROJECT_SELECTION_DROPDOWN = 'PROJECT_SELECTION_DROPDOWN',
  SESSION_TYPE_DROPDOWN = 'SESSION_TYPE_DROPDOWN',
  EXISTING_SESSION_DROPDOWN_SELECTION = 'EXISTING_SESSION_DROPDOWN_SELECTION',
}

export enum SLACK_DROPDOWN_BLOCK_ID {
  SELECT_PROJECT_BLOCK = 'SELECT_PROJECT_BLOCK',
  SESSION_TYPE_BLOCK = 'session_type_block',
}

export enum SLACK_BLOCKS {
  SAVE_CONFIG_BUTTON_BLOCK = 'SAVE_CONFIG_BUTTON_BLOCK',
  UPDATE_CONFIG_BUTTON_BLOCK = 'UPDATE_CONFIG_BUTTON_BLOCK',
  BASE_URL_INPUT_BLOCK = 'BASE_URL_INPUT_BLOCK',
  API_KEY_INPUT_BLOCK = 'API_KEY_INPUT_BLOCK',
  EDIT_CONFIG_BUTTON_BLOCK = 'EDIT_CONFIG_BUTTON_BLOCK',
}

export const SESSION_TYPE_KEYS = {
  NEW_SESSION: 'new_session',
  EXISTING_SESSION: 'existing_session',
};

export const SESSION_TYPE = [
  {key: SESSION_TYPE_KEYS.NEW_SESSION, label: 'New Session'},
  {key: SESSION_TYPE_KEYS.EXISTING_SESSION, label: 'Existing Session'},
];

export enum MessageContentType {
  CONTENT_TYPE_UNSPECIFIED = 'CONTENT_TYPE_UNSPECIFIED',
  CONTENT_TYPE_DONE_INDICATOR = 'CONTENT_TYPE_DONE_INDICATOR',
  CONTENT_TYPE_PROGRESS_STATUS = 'CONTENT_TYPE_PROGRESS_STATUS',
  CONTENT_TYPE_CHAT_PROMPT = 'CONTENT_TYPE_CHAT_PROMPT',
  CONTENT_TYPE_CHAT_RESPONSE = 'CONTENT_TYPE_CHAT_RESPONSE',
  CONTENT_TYPE_FOLLOW_UP_SUGGESTIONS = 'CONTENT_TYPE_FOLLOW_UP_SUGGESTIONS',
  CONTENT_TYPE_VISUALIZATION = 'CONTENT_TYPE_VISUALIZATION',
  CONTENT_TYPE_SESSION_NAME = 'CONTENT_TYPE_SESSION_NAME',
  CONTENT_TYPE_SOURCES = 'CONTENT_TYPE_SOURCES',
  CONTENT_TYPE_CHAIN_OF_THOUGHT = 'CONTENT_TYPE_CHAIN_OF_THOUGHT',
  CONTENT_TYPE_ALTERNATE_QUESTIONS = 'CONTENT_TYPE_ALTERNATE_QUESTIONS',
  CONTENT_TYPE_ERROR_MESSAGE = 'CONTENT_TYPE_ERROR_MESSAGE',
  CONTENT_TYPE_EXECUTION_TIME = 'CONTENT_TYPE_EXECUTION_TIME',
}

export const linkAuthRoute = '/console';
export const linkProjectBase = 'project';
export const linkProjectChat = '/session';
export const linkUsage = '/usage';
