import arg from 'arg';
import fs from 'fs-extra';
import { ClassDeclaration, Project, SourceFile } from 'ts-morph';

const OBJECT_TYPE = { ENTITY: 'ENTITY', DTO: 'DTO' };
const UNKNOWN = 'UNKNOWN';
const DEFAULT_SOURCE_FOLDER = './src/entity/**/*.ts';
const DEFAULT_DESCRIPTOR_DESTINATION_FOLDER = 'src/util/entity-descriptor.ts';
const DEFAULT_OBJECT_TYPE = OBJECT_TYPE.ENTITY;

const cleanFile = (filePath: string): void => {
  fs.ensureFileSync(filePath);
  fs.writeFileSync(filePath, '');
  appendToFile(filePath, `/* This is an autogenerated file. Please do not edit directly. */`);
};

const appendToFile = (filePath: string, content: string): void => {
  fs.writeFileSync(filePath, content, { flag: 'a' });
  fs.writeFileSync(filePath, '\n\n', { flag: 'a' });
};

const prepareHierarchyMap = (sourceFiles: SourceFile[]): Map<string, ClassDeclaration> => {
  let map: Map<string, ClassDeclaration> = new Map();
  for (const sourceFile of sourceFiles) {
    const node = sourceFile.getClasses()[0];
    map.set(node.getName() ?? 'UNKNOWN', node);
  }
  return map;
};

const getDescriptorDetails = (
  classMap: Map<string, ClassDeclaration>,
  node: ClassDeclaration,
  className: string = UNKNOWN,
  definition: any,
): any => {
  let extendsClassName = node.getStructure().extends?.toString() ?? undefined;
  let extendsClass: ClassDeclaration | undefined = node.getBaseClass();

  if (extendsClassName && classMap) {
    extendsClass = classMap.get(extendsClassName);
  }

  let baseClass: ClassDeclaration | undefined = extendsClass;
  //console.log(baseClass?.getName() ?? 'No Base Class found for ' + node.getName());

  if (definition) {
  } else {
    definition = {
      FIELDS: {},
      CLASS_NAME: '',
      CLASS_HIERARCHY: [],
    };
  }
  if (baseClass) {
    definition = getDescriptorDetails(classMap, baseClass, className, definition);
    //definition.CLASS_HIERARCHY.push(baseClass.getName());
  }
  const allKeys = node.getProperties().map(p => p.getName());
  for (const property of node.getProperties()) {
    let fieldDescription: any = {};
    fieldDescription.name = property.getName();
    fieldDescription.isForeignKey = false;
    fieldDescription.type = property?.getType()?.getText() ?? UNKNOWN;
    // sometimes, getting file_path.className
    if (fieldDescription.type) {
      let fullType = fieldDescription.type.split('.');
      fieldDescription.type = fullType[fullType.length - 1];
      if (classMap.get(fieldDescription.type)) fieldDescription.isForeignKey = true;
    }
    fieldDescription.decorators =
      property.getDecorators()?.map(decorator => {
        return { name: decorator.getName(), args: decorator.getArguments()?.map(argument => argument.getText()) };
      }) ?? [];
    if (className === node.getName()) {
      fieldDescription.isInherited = false;
      fieldDescription.inheritedFromClassName = '';
    } else {
      fieldDescription.isInherited = true;
      fieldDescription.inheritedFromClassName = node.getName();
    }
    definition.FIELDS[property.getName()] = fieldDescription;
  }
  if (className) definition.CLASS_NAME = className;
  if (node?.getName() && className && node.getName() && node.getName() !== className)
    definition.CLASS_HIERARCHY.push(node?.getName());
  ////console.log(definition);

  return definition;
};
// initName is name of the interface file below the root, ./src is considered the root
const prepareDescriptor = (args: Args): void => {
  const project = new Project();

  let objectType = args.objectType.toUpperCase();

  let sources = [];
  if (args.includeCommon) {
    if (objectType === OBJECT_TYPE.ENTITY) {
      sources.push('./node_modules/@kaiju-lib/node-common/src/common/entity/**/*.ts');
    }
  }
  sources.push(args.sourcePath);
  console.log('Sources=', sources);

  const sourceFiles = project.addSourceFilesAtPaths(sources);
  let classMap = prepareHierarchyMap(sourceFiles);
  cleanFile(args.destinationPath);

  let allEntitiesMapName = `${objectType}_DESCRIPTOR_MAP`;

  if (sourceFiles && sourceFiles.length > 0) {
    let docsForDescriptorMap = `
    /**
    * Use as follows:
    * ${objectType}_DESCRIPTOR_MAP.get(<ClassName>Descriptor.CLASS_NAME);
    * e.g. : 
    * ${objectType}_DESCRIPTOR_MAP.get(SampleDescriptor.CLASS_NAME);
    * ${objectType}_DESCRIPTOR_MAP.get(UserDescriptor.CLASS_NAME);
    */
   `;
    appendToFile(args.destinationPath, docsForDescriptorMap);
    appendToFile(args.destinationPath, `export const ${allEntitiesMapName}:Map<string,any> = new Map();`);
    for (const sourceFile of sourceFiles) {
      //const sourceFile = project.addSourceFileAtPath(`./src/entity/${intName}.ts`);
      const node = sourceFile.getClasses()[0];
      console.log(`Processing ${node.getName()}`);
      let descriptor = getDescriptorDetails(classMap, node, node.getName(), null);
      //console.log(descriptor);
      if (descriptor) {
        let constName = `${node.getName()}Descriptor`;
        let content = `export const ${constName} = ${JSON.stringify(descriptor)}`;
        appendToFile(args.destinationPath, content);

        appendToFile(args.destinationPath, `${allEntitiesMapName}.set('${node.getName()}', ${constName})`);
      }
    }
  }
};

function parseArgumentsIntoOptions(rawArgs: any) {
  const args = arg(
    {
      '--src': String,
      '--out': String,
      '--type': String,
      '--include-common': Boolean,
      '-s': '--src',
      '-o': '--out',
      '-t': '--type',
      '-c': '--include-common',
    },
    {
      argv: rawArgs.slice(2),
      permissive: true,
    },
  );
  return {
    sourcePath: args['--src'] || DEFAULT_SOURCE_FOLDER,
    destinationPath: args['--out'] || DEFAULT_DESCRIPTOR_DESTINATION_FOLDER,
    objectType: args['--type'] || DEFAULT_OBJECT_TYPE,
    includeCommon: args['--include-common'] || false,
  };
}

interface Args {
  sourcePath: string;
  destinationPath: string;
  objectType: string;
  includeCommon: boolean;
}

const run = () => {
  //console.log(process.argv);
  console.log('Starting Code Gen');
  let args = parseArgumentsIntoOptions(process.argv);
  console.log('Arguments=', args);

  prepareDescriptor(args);
  console.log('Completed Code Gen');
};

run();
