name: Build & Deploy image

on: 
  push: 
    branches: [ "dev" ] 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.NEUBIRD_SLACK }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

    #  - name: Authenticate npm with GitHub Token
    #    run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NEUBIRD_SLACK }}" > ~/.npmrc

      # Step to install dependencies
      - name: Install dependencies
        run: |
          npm cache clean --force && npm run init


      # Step to build the source code
      - name: Build the app
        run: |
          npm run build  

          
      - name: Build docker image
        run: |
          docker build . -t neubirdai/hawkeye-slack:build

      - name: Set Build Timestamp
        id: set_timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d-%s')"
